server:
  port: 8081


spring:
  datasource:
    url: jdbc:h2:mem:website
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      path: /h2-console
      enabled: true
